Repository wpovernight/woocommerce-pdf-invoices-packing-slips, pull requests merged in 2024-01, with the labels that each got.

#683 Declare new "Payment Date:" string
  languages/strings.php
Labels: i18n

#687 Declare new "Payment Date:" string (II)
  languages/strings.php
Labels: i18n

#695 Make translatable the due date output
  includes/class-wcpdf-main.php
Labels: bug, i18n

#698 Fix the level parameter sent to the log() method
  includes/class-wcpdf-updraft-semaphore.php
Labels: bug

#700 Fix sorting orders by invoice number and date issue on the orders page
  includes/class-wcpdf-admin.php
Labels: bug
