Repository wpovernight/woocommerce-pdf-invoices-packing-slips, pull requests merged in 2024-07, with the labels that each got.

#828 Add row classes for "YITH WooCommerce Product Bundles"
  includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
Labels: enhancement

#814 Wrap address around P tag
  templates/Simple/invoice.php
  templates/Simple/packing-slip.php
Labels: enhancement

#804 HPOS: add Invoice number to search type selector #748
  includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php
  includes/documents/class-wcpdf-invoice.php
Labels: enhancement, week task

#831 Make totals labels translatable
  includes/documents/abstract-wcpdf-order-document-methods.php
Labels: bug, week task

#826 Tweak: improved header logo loading
  includes/class-wcpdf-settings.php
  includes/documents/abstract-wcpdf-order-document.php
  includes/makers/class-pdf-maker.php
  includes/settings/class-wcpdf-settings-debug.php
  includes/views/advanced-status.php
  includes/wcpdf-functions.php
  woocommerce-pdf-invoices-packingslips.php
Labels: compatibility

#818 New: PDFJS v4.3.136 upgrade
  assets/js/admin-script.js
  assets/js/admin-script.min.js
  assets/js/pdf_js/pdf.min.js
  assets/js/pdf_js/pdf.worker.min.js
  includes/class-wcpdf-assets.php
Labels: enhancement

#845 Apply a filter to modify PDF document data fields
  includes/class-wcpdf-admin.php
Labels: enhancement
