Repository wpovernight/woocommerce-pdf-invoices-packing-slips, pull requests merged in 2024-06, with the labels that each got.

#792 Remove unwanted tags from `wpo_wcpdf_sanitize_html_content()`
  includes/documents/abstract-wcpdf-order-document-methods.php
  includes/wcpdf-functions.php
Labels: bug, week task

#803 Fix: Number formatting `[order_number]` placeholder not using parent order number on Credit Notes
  includes/documents/class-wcpdf-document-number.php
Labels: bug

#820 New: adds filter hooks to `i18n_wrap` to extend languages to third parties
  includes/settings/class-wcpdf-settings-callbacks.php
  includes/wcpdf-functions.php
  woocommerce-pdf-invoices-packingslips.php
Labels: week task

#821 Tweak: improvements on notes for translations
  includes/documents/abstract-wcpdf-order-document-methods.php
Labels: week task

#822 Tweak: improves specific strings registration
  languages/strings.php
  templates/Simple/invoice.php
  templates/Simple/packing-slip.php
Labels: week task

#824 Fix `normalize_settings_args` bug
  includes/settings/class-wcpdf-settings-callbacks.php
Labels: bug, week task

#817 Register a log for document deletion in the Order Notes
  includes/class-wcpdf-main.php
  includes/settings/class-wcpdf-settings-debug.php
Labels: enhancement
