Repository wpovernight/woocommerce-pdf-invoices-packing-slips, pull requests merged in 2024-10, with the labels that each got.

#850 Add 'You might also like' section to the Upgrade tab.
  assets/css/settings-styles.css
  assets/css/settings-styles.min.css
  assets/images/wc-reminder-emails-thumbnail-400x400.jpg
  assets/images/woocommerce-address-labels-thumbnail-400x400.jpg
  assets/images/woocommerce-order-list-thumbnail-400x400.jpg
  assets/images/woocommerce-printnode-thumbnail-400x400.jpg
  assets/images/woocommerce-ultimate-barcodes-thumbnail-400x400.jpg
  assets/images/wp-menu-cart-pro-thumbnail-400x400.jpg
  includes/class-wcpdf-settings.php
  includes/settings/class-wcpdf-settings-upgrade.php
  includes/views/upgrade-table.php
Labels: enhancement

#872 Check current user role in the `enable_debug` function
  includes/class-wcpdf-main.php
Labels: security

#873 Update due date hooks
  includes/documents/abstract-wcpdf-order-document.php
Labels: bug

#869 Remove path to generic_document.png
  assets/images/generic_document.svg
  includes/class-wcpdf-admin.php
Labels: enhancement

#877 Fix deprecated function usage
  assets/js/admin-script.js
  assets/js/admin-script.min.js
Labels: enhancement

#810 New: adds full compatibility with mPDF to the Simple Template
  templates/Simple/invoice.php
  templates/Simple/packing-slip.php
  templates/Simple/style.css
Labels: enhancement, week task

#884 Deprecate `wpo_wcpdf_due_date_display` hook
  includes/Main.php
Labels: enhancement
