Repository wpovernight/woocommerce-pdf-invoices-packing-slips, pull requests merged in 2025-01, with the labels that each got.

#963 Add global helper functions for UBL
  ubl/Handlers/Common/AdditionalDocumentReferenceHandler.php
  ubl/Handlers/Common/AddressHandler.php
  ubl/Handlers/Invoice/InvoiceLineHandler.php
  woocommerce-pdf-invoices-packingslips.php
  wpo-ips-functions-ubl.php
Labels: enhancement

#993 Fix setting categories not applied for disabled documents
  includes/Settings.php
Labels: bug

#1023 Add Lithuanian language pack (document strings only)
  languages/woocommerce-pdf-invoices-packing-slips-lt_LT.mo
  languages/woocommerce-pdf-invoices-packing-slips-lt_LT.po
Labels: translations

#1022 Remove translatability from VAT and COC fields
  includes/Install.php
  includes/Settings/SettingsGeneral.php
  woocommerce-pdf-invoices-packingslips.php
Labels: enhancement
