Repository wpovernight/woocommerce-pdf-invoices-packing-slips, pull requests merged in 2025-02, with the labels that each got.

#1046 Check if `is_enabled()` is callable for the document in `wcpdf_get_document_file()`
  wpo-ips-functions.php
Labels: bug

#1039 Add document link to emails for guest customers
  includes/Assets.php
  includes/Documents/Invoice.php
  includes/Endpoint.php
  includes/Main.php
  includes/Settings/SettingsCallbacks.php
  includes/Settings/SettingsDebug.php
Labels: enhancement

#1057 Use `wp_kses_post` instead of `wpo_wcpdf_sanitize_html_content` for footer & extras
  includes/Documents/OrderDocument.php
Labels: enhancement

#1059 Display "Plugins Version" table under Status tab
  assets/css/settings-styles.css
  assets/css/settings-styles.min.css
  includes/Settings/SettingsDebug.php
  views/advanced-status.php
Labels: enhancement

#1064 Apply `wpautop()` to document notes
  includes/Documents/OrderDocumentMethods.php
Labels: enhancement

#1065 Clean up special characters in `get_html()` of Bulk Document
  includes/Documents/BulkDocument.php
Labels: bug

#755 Fix: issues rendering the number tab results
  assets/css/settings-styles.css
  assets/css/settings-styles.min.css
  assets/js/debug-script.js
  assets/js/debug-script.min.js
  includes/Settings/SettingsDebug.php
  includes/Tables/NumberStoreListTable.php
  views/advanced-numbers.php
  views/advanced-status.php
Labels: bug, week task

#1073 Show inactive status for packing slip yearly reset
  assets/css/settings-styles.css
  assets/css/settings-styles.min.css
  includes/Settings/SettingsDebug.php
  views/advanced-status.php
Labels: enhancement
